openapi: 3.0.3
info:
  description : API Twitter Lite
  title: Twitter
  version: 1.0.0
  contact:
    name: Twitter Developers
    url: https://developer.twitter.com/
paths:
  /users:
    get:
      summary: Return details for the specified users
      description: This endpoint returns information about users. Specify users by their ID.
      operationId: findUsersById
      parameters:
        - name: ids
          in: query
          description: Required. A list of User IDs, comma-separated. You can specify up to 100 IDs.
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserID'
            minItems: 1
            maxItems: 100
      responses:
        '200':
          description: The request was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLookupResponse'
  /users/{id}:
    get:
      summary: Return details for the specified users
      description: This endpoint returns information about a user. Specify user by ID.
      operationId: findUserById
      parameters:
        - name: id
          in: path
          description: Required. A User ID.
          required: true
          schema:
            $ref: '#/components/schemas/UserID'
      responses:
        '200':
          description: The request was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleUserLookupResponse'
  /labs/2/tweets:
    get:
      summary: Returns hydrated Tweet objects
      description: Returns a variety of information about the Tweet specified by the requested ID
      operationId: findTweetsById
      parameters:
        - name: ids
          in: query
          description: A comma separated list of Tweet IDs. Up to 100 are allowed in a single request.
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/TweetID'
            minItems: 1
            maxItems: 100
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TweetLookupResponse'
  /labs/2/tweets/id:
    get:
      summary: Returns hydrated Tweet objects
      description: Returns a variety of information about the Tweet specified by the requested ID
      operationId: findTweetById
      parameters:
        - name: id
          in: path
          description: A single Tweet ID.
          required: true
          schema:
            $ref: '#/components/schemas/TweetID'
      responses:
        200:
          description: The request was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleTweetLookupResponse'
components:
  schemas:
    TweetID:
      type: string
      description: Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
      pattern: ^[0-9]119}$
      example: 120897978112909812
    UserID:
      type: string
      description: Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
      pattern: ^[0-9]119}$
      example: 712089797812
    UserLookupResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/User'
          minItems: 1
    SingleUserLookupResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/User'
    TweetLookupResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Tweet'
          minItems: 1
    SingleTweetLookupResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Tweet'
    User:
      description: The Twitter User object
      properties:
        id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
          description: Creation time of this user.
        name:
          type: string
          description: The friendly name of this user as shown on their profile.
        username:
          type: string
        protected:
          type: boolean
          description: Indicates if this user has chosen to protect their Tweets (in other words if this user's Tweets are private).
        verified:
          type: boolean
          description: Indicate if this user is a verified Twitter User.
        profile_image_url:
          type: string
          description: The URL to the profile image for this user.
          format: uri
        location:
          type: string
          description: The location specified in the user's profile if the user provided one. As this is a freeform value it may not indicate a valid location but it may be fuzzily evaluated when performing searches with location queries.
        url:
          type: string
          description: The URL specified in the user's profile.
        description:
          type: string
          description: The text of this user's profile description (also known as bio) if the user provided one.
    Tweet:
      description: The Twitt object
      properties:
        id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
          description: Creation time of the Tweet.
        text:
          type: string
          description: The content of the Tweet.
        possibly_sensitive:
          type: boolean
          description: Indicates if this Tweet contains URLs marked as sensitive for example content suitable for mature audiences.
        lang:
          type: string
          description: Language of the Tweet if detected by Twitter. Returned as a BCP47 language tag.
        source:
          type: string
          description: The name of the app the user Tweeted from.
        non_public_metrics:
          type: object
          description: Nonpublic engagement metrics for the Tweet at the time of the request.
          properties:
            impression_count:
              type: integer
              format: int32
              description: Number of times this Tweet has been viewed.
            user_profile_clicks:
              type: integer
              description: Number of times the user's profile from this Tweet has been clicked.
            url_link_clicks:
              type: integer
              description: Number of times links in this Tweet have been clicked.
        promoted_metrics:
          type: object
          description: Promoted nonpublic engagement metrics for the Tweet at the time of the request.
          properties:
            impression_count:
              type: integer
              format: int32
              description: Number of times this Tweet has been viewed.
            like_count:
              type: integer
              format: int32
              description: Number of times this Tweet has been liked.
            reply_count:
              type: integer
              format: int32
              description: Number of times this Tweet has been replied to.
            retweet_count:
              type: integer
              format: int32
              description: Number of times this Tweet has been Retweeted.
            user_profile_clicks:
              type: integer
              description: Number of times the user's profile from this Tweet has been clicked.
            url_link_clicks:
              type: integer
              description: Number of times links in this Tweet have been clicked.
        organic_metrics:
          type: object
          description: Organic nonpublic engagement metrics for the Tweet at the time of the request.
          required: [ impression_count retweet_count reply_count like_count user_profile_clicks]
          properties:
            impression_count:
              type: integer
              description: Number of times this Tweet has been viewed.
            retweet_count:
              type: integer
              description: Number of times this Tweet has been Retweeted.
            reply_count:
              type: integer
              description: Number of times this Tweet has been replied to.
            like_count:
              type: integer
              description: Number of times this Tweet has been liked.
            user_profile_clicks:
              type: integer
              description: Number of times the user's profile from this Tweet has been clicked.
            url_link_clicks:
              type: integer
              description: Number of times links in this Tweet have been clicked.
